embed_assets: on

javascripts:
  workspace:
    - public/javascripts/vendor/*.js
    - public/javascripts/lib/*.js
    # - app/assets/javascripts/views/*.jst
    - public/javascripts/application.js        
